import { useEffect } from "react";
// Trường hợp: static html generation (không dùng getStaticProps, getStaticPaths, getServerSideProps trong component)
// -> thì khi npm run build or yarn build sau đó start thì nó sẽ tự động chuyển trang của mình thành file .html, khi user request thì nó đã tạo sẵn file .html, chỉ hiển thị ra mà thôi
// Trường hợp: static html + json data (dùng getStaticProps)
// Trường hợp: static html + json data + dynamic routes (dùng getStaticProps + getStaticPaths)
// Chỉ sử dụng getStaticProps + getStaticPath (2 thằng này là SSG) hoặc getServerSideProps () -> không dùng chung
// có staticProps và staticPath thì không có serverSideProp và ngược lại.
// chỉ sử dụng được 3 hàm này trong page (những component nằm trong folder pages), còn những component 
// chia nhỏ nằm ngoài folder pages thì k dùng dc, chính vì vậy người ta thường sử dụng trong page rồi 
// truyền data vào các component con, 
// 3 hàm trên ở server-side (chỉ chạy ở phía server, client có console.log cũng không thấy) và chỉ chạy lúc build-time (khi npm run build or yarn build)
// trong môi trường dev thì chỉ cần gủi request thì nó luôn luôn chạy 3 hàm này
import Head from "next/head";
// instead
// function useUser() {
//     // return useSWR('/users', fetcher)
//     return useSWR('/url-api')
// }
// import useSWR from "swr"; // install library
const SWR = () => {
  // SWR là một thư viện React Hooks dùng trong việc fetch data.
  // const {data, error, isValidating} = useUser;
  // useEffect(() => {
  //     if(data) {
  //         setArrayAPI(data);
  //     }
  // }, [data]);
  // if(error) {
  //     return <p>Failed to load.</p>
  // }
  // if(!data && !arrayAPI) {
  //     return <p>Loading...</p>
  // }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="title" content="" />
        <meta property="fb:app_id" content="" />
        <meta property="twitter:url" content="" />
        <meta property="og:type" content="" />
        <meta property="og:site_name" content="" />
        <meta property="og:locale" content="" />
        <meta property="og:title" content="" />
        <meta property="og:description" content="" />
        <meta property="og:image" content="" />
        <meta property="og:image:secure" content="" />
        <meta name="og:url" content="" />
      </Head>
    </div>
  );
};
export default SWR;
